services:
  app:
    build: .
    container_name: laravel-frankenphp
    ports:
      - "80:8001"
      - "443:8001"
    volumes:
      - .:/app
      - ./Caddyfile:/etc/caddy/Caddyfile 
    extra_hosts:
      - "host.docker.internal:host-gateway"
